IonosLedWebMvc.Ver2/Models/Entities/LampModel.cs
using System;
using System.Collections.Generic;

namespace IonosLedWebMvc.Ver2.Models.Entities;

public partial class LampModel
{
    public uint Id { get; set; }
    public string ModelName { get; set; } = null!;
    public byte Sections { get; set; }

    public decimal CutPrice { get; set; }

    public decimal DrillPrice { get; set; }

    public decimal MountPrice { get; set; }

    public decimal SolderPrice { get; set; }

    public decimal AssemblyPrice { get; set; }

    public decimal CheckPrice { get; set; }

    public virtual ICollection<LedLamp> ProductsLedLights { get; set; } = new List<LedLamp>();
}

IonosLedWebMvc.Ver2/Models/LampModel.cs
using System;
using System.Collections.Generic;

namespace IonosLedWebMvc.Ver2.Models;

public partial class LampModel
{
    public uint Id { get; set; }
    public string ModelName { get; set; } = null!;
    public byte Sections { get; set; }

    public decimal CutPrice { get; set; }

    public decimal DrillPrice { get; set; }

    public decimal MountPrice { get; set; }

    public decimal SolderPrice { get; set; }

    public decimal AssemblyPrice { get; set; }

    public decimal CheckPrice { get; set; }

    public virtual ICollection<LedLamp> ProductsLedLights { get; set; } = new List<LedLamp>();
}

IonosLedWebMvc.Ver2/Controllers/LampModelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IonosLedWebMvc.Ver2.Data;
using IonosLedWebMvc.Ver2.Dtos;
using IonosLedWebMvc.Ver2.Services;
using IonosLedWebMvc.Ver2.Models;
using IonosLedWebMvc.Ver2.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace IonosLedWebMvc.Ver2.Controllers
{
    public class LampModelController : Controller
    {
        private const string PREFIX_OK_RESULT = "Поздравляем! ";
        private const string PREFIX_BAD_RESULT = "Готово! ";
        private readonly ApplicationContext _context;
        private readonly LampService _lampService;
        private readonly LampModelService _lampModelService;

        public LampModelController(ApplicationContext context, LampService lampService, LampModelService lampModelService)
        {
            _context = context;
            _lampService = lampService;
            _lampModelService = lampModelService;
        }

        // GET: LampModel
        public async Task<IActionResult> Index(string? userActionResult)
        {
            var models = await _context.LampModels.ToListAsync();
            var modelNameToCount = await _lampService.GetCountedModelsAsync();
            ViewData["UserActionResult"] = userActionResult;
            ViewData["OK"] = PREFIX_OK_RESULT;
            return View(models.Select(m => LampModelDto.FromLampModel(m, modelNameToCount)).OrderByDescending(m => m.CountReleased));
        }



		// GET: LampModel/Create
		[Authorize]
		public IActionResult Create()
        {
            return View();
        }

        // POST: LampModel/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,ModelName,Sections,CutPrice,DrillPrice,MountPrice,SolderPrice,AssemblyPrice,CheckPrice")] LampModelDto lampModelDto)
        {
            if (ModelState.IsValid)
            {
                _context.LampModels.Add(LampModelDto.ToLampModel(lampModelDto));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userActionResult = $"{PREFIX_OK_RESULT} Модель успешно создана." });
            }
            return View(lampModelDto);
        }

        // GET: LampModel/Edit/5
        // resultFilesInfo - параметр вида "resultUploads;FileName1,FileExtensions1,FileSize1;FileName2,FileExtensions2,FileSize2;..."
        [Authorize]
		public async Task<IActionResult> Edit(uint? id, string? resultImgUpload, string? resultFilesUpload, string? resultNoteAdded)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foundModel = await _context.LampModels.FindAsync(id);
            if (foundModel == null)
            {
                return NotFound();
            }
            ViewBag.ImgUploadSuccess = resultImgUpload;
            ViewBag.FilesUploadSuccess = resultFilesUpload;
            ViewBag.AddNoteSuccess = resultNoteAdded;

            
            var filesWithSizesAsStr = await _lampModelService.GetAllFilesByModelId(id);
            List<FileRecordForView> fileRecords = _lampModelService.ParseFileRecordDB(filesWithSizesAsStr, (int)id);
            ViewBag.FileRecords = fileRecords; 

            return View(LampModelDto.FromLampModel(foundModel));
        }

        // POST: LampModel/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Authorize]
		public async Task<IActionResult> Edit(uint id, [Bind("Id,ModelName,Sections,CutPrice,DrillPrice,MountPrice,SolderPrice,AssemblyPrice,CheckPrice")] LampModelDto lampModelDto)
        {
            if (id != lampModelDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currModel = LampModelDto.ToLampModel(lampModelDto);
					currModel.Id = id;
                    _context.LampModels.Update(currModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LampModelExists(lampModelDto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { userActionResult = $"{PREFIX_OK_RESULT} Данные модели успешно изменены." });
            }
            return View(lampModelDto);
        }

		// GET: LampModel/Delete/5
		[Authorize]
		public async Task<IActionResult> Delete(uint? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foundModel = await _context.LampModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foundModel == null)
            {
                return NotFound();
            }

            return View(LampModelDto.FromLampModel(foundModel));
        }

        // POST: LampModel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Authorize]
		public async Task<IActionResult> DeleteConfirmed(uint id)
        {
            var foundModel = await _context.LampModels.FindAsync(id);
            if (foundModel != null)
            {
                _context.LampModels.Remove(foundModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { userActionResult = $"{PREFIX_BAD_RESULT} Модель удалена." });
        }



        // GET: LampModel/Details/5
        public async Task<IActionResult> Details(uint? id, string modelId, string? startDate, string? endDate, int pageNumber)
        {
            int correctPageNumber = pageNumber < 1 ? 1 : pageNumber;

            if (id == null) {
                return NotFound();
            }

            var lampModel = await _context.LampModels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lampModel == null) {
                return NotFound();
            }

            var lampModelDetails = await _context.LampModelDetails.FirstOrDefaultAsync(m => m.LampModelId == (int)id);
            ViewData["ImageName"] = lampModelDetails?.ImageName;
            var filesWithSizesAsStr = await _lampModelService.GetAllFilesByModelId(id);
            List<FileRecordForView> fileRecords = _lampModelService.ParseFileRecordDB(filesWithSizesAsStr, (int)id);
            ViewBag.FileRecords = fileRecords;

            if (startDate == null && endDate == null) {
                ViewBag.StartDate = $"{DateTime.Now.Date:s}";
                ViewBag.EndDate = $"{DateTime.Now.Date:s}";
                return View(new LampModelDetailsPageDto(LampModelDto.FromLampModel(lampModel, notes: lampModelDetails?.Note), null));
            }
            // если применяем фильтрацию, то Id получаем через скрытое строковое поле modelId
            var mId = uint.Parse(modelId);
            DateTime endDt = DateTime.Parse(endDate);
            DateTime startDt = DateTime.Parse(startDate);
            ViewBag.StartDate = $"{startDt:s}";
            ViewBag.EndDate = $"{endDt:s}";
            var lamps = _lampService.GetAllByModelAndDate(mId, startDt, endDt);

            int pageSize = 40;
            var lampsPaginated = await PaginatedList<LedLamp>.CreateAsync(lamps, correctPageNumber, pageSize);

            // для расчета полученного числа записей необходимо получить значение колличества записей на последней странице, т.к. она может не полная
            var lastPageNumber = lampsPaginated.TotalPages < 1 ? 1 : lampsPaginated.TotalPages;
            var lastPage = await PaginatedList<LedLamp>.CreateAsync(lamps, lastPageNumber, pageSize);
            var totalRecords = lampsPaginated.TotalPages * pageSize - (pageSize - lastPage.Items.Count);
            ViewBag.TotalRecords = totalRecords < 0 ? 0 : totalRecords;

            return View(new LampModelDetailsPageDto(LampModelDto.FromLampModel(lampModel, notes: lampModelDetails?.Note), lampsPaginated));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ImageUpload(IFormFile imageFile, uint id)
        {
            if (ModelState.IsValid) {
                //Save image to wwwroot/image
                string result = await _lampModelService.SaveOrChangeImageFile(imageFile, id);
                //Insert record
                //_context.Add(imageModel);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Edit), new { id = id, resultImgUpload = result });
            }
            return RedirectToAction(nameof(Edit), new { id = id });
        }

        [Authorize]
        [HttpPost("FilesUpload")]
        public async Task<IActionResult> FilesUpload(List<IFormFile> files, uint id)
        {
            if (ModelState.IsValid && files.Count > 0) {
                var resultUpload = await _lampModelService.SaveFiles(files, id);
                return RedirectToAction(nameof(Edit), new { id = id, resultFilesUpload = resultUpload });
            }
            return RedirectToAction(nameof(Edit), new { id = id });

            // process uploaded files
            // Don't rely on or trust the FileName property without validation.
            /*return Ok(new { count = files.Count, size, filePaths });*/
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddNote(string noteArea, uint id)
        {

IonosLedWebMvc.Ver2/Views/LampModel/Create.cshtml
@model IonosLedWebMvc.Ver2.Dtos.LampModelDto

@{
    ViewData["Title"] = "CreateLampModel";
}

<h1>Создание</h1>

<h4>Данные модели:</h4>
<div class="info-create">
    <p><strong>Информация!</strong> После сохранения основной информации, перейдите в режим редактирования для добавления изображения и других данных...</p>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModelName" class="control-label"></label>
                <input asp-for="ModelName" class="form-control" />
                <span asp-validation-for="ModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sections" class="control-label"></label>
                <input asp-for="Sections" class="form-control" />
                <span asp-validation-for="Sections" class="text-danger"></span>
            </div>
            <p class="cost-works">Стоимости видов работ:</p>
            <hr />
            <div class="form-group">
                <label asp-for="CutPrice" class="control-label"></label>
                <input asp-for="CutPrice" class="form-control" />
                <span asp-validation-for="CutPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrillPrice" class="control-label"></label>
                <input asp-for="DrillPrice" class="form-control" />
                <span asp-validation-for="DrillPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MountPrice" class="control-label"></label>
                <input asp-for="MountPrice" class="form-control" />
                <span asp-validation-for="MountPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolderPrice" class="control-label"></label>
                <input asp-for="SolderPrice" class="form-control" />
                <span asp-validation-for="SolderPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssemblyPrice" class="control-label"></label>
                <input asp-for="AssemblyPrice" class="form-control" />
                <span asp-validation-for="AssemblyPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckPrice" class="control-label"></label>
                <input asp-for="CheckPrice" class="form-control" />
                <span asp-validation-for="CheckPrice" class="text-danger"></span>
            </div>
            <div class="form-group fix-btn-create">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IonosLedWebMvc.Ver2/Views/LampModel/Delete.cshtml
@model IonosLedWebMvc.Ver2.Dtos.LampModelDto

@{
    ViewData["Title"] = "DeleteLampModel";
}

<h1 class="delete-title">Вы уверены, что хотите удалить выбранную модель?</h1>

<div>
    <h4>Данные модели:</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sections)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sections)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CutPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CutPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DrillPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DrillPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MountPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MountPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SolderPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SolderPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssemblyPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssemblyPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад к списку</a>
    </form>
</div>

IonosLedWebMvc.Ver2/Views/LampModel/Edit.cshtml
@model IonosLedWebMvc.Ver2.Dtos.LampModelDto

@{
    ViewData["Title"] = "EditLampModel";
}

<h1>Редактирование</h1>

<h4>Данные модели:</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="ModelName" class="control-label"></label>
                        <input asp-for="ModelName" class="form-control" />
                        <span asp-validation-for="ModelName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Sections" class="control-label"></label>
                        <input asp-for="Sections" class="form-control" />
                        <span asp-validation-for="Sections" class="text-danger"></span>
                    </div>
                    <p class="cost-works">Стоимости видов работ:</p>
                    <hr />
                    <div class="form-group">
                        <label asp-for="CutPrice" class="control-label"></label>
                        <input asp-for="CutPrice" class="form-control" />
                        <span asp-validation-for="CutPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DrillPrice" class="control-label"></label>
                        <input asp-for="DrillPrice" class="form-control" />
                        <span asp-validation-for="DrillPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MountPrice" class="control-label"></label>
                        <input asp-for="MountPrice" class="form-control" />
                        <span asp-validation-for="MountPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SolderPrice" class="control-label"></label>
                        <input asp-for="SolderPrice" class="form-control" />
                        <span asp-validation-for="SolderPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="AssemblyPrice" class="control-label"></label>
                        <input asp-for="AssemblyPrice" class="form-control" />
                        <span asp-validation-for="AssemblyPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CheckPrice" class="control-label"></label>
                        <input asp-for="CheckPrice" class="form-control" />
                        <span asp-validation-for="CheckPrice" class="text-danger"></span>
                    </div>

                    <div class="form-group fix-btn-create">
                        <input type="submit" value="Сохранить" class="btn btn-primary" /> | <a asp-action="Index">Назад к списку</a>
                    </div>

                </form>


            </div>
        </div>
    </div>

    <div class="col-md-4">

        <div class="row">
            <div class="col-md-12">
                <form method="post" asp-controller="LampModel" asp-action="ImageUpload" enctype="multipart/form-data">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <label for="imageFile"><b>Выберите основное изображение формата .jpg,.png,.gif</b></label>
                    <input type="file" name="imageFile" accept=".jpg,.png,.gif" class="form-control" />

                    <input type="hidden" name="id" value="@Model.Id" />

                    <button type="submit" class="btn btn-primary fix-btn-create">Загрузить</button>
                    <span class="text-success">@ViewBag.ImgUploadSuccess</span>
                </form>
            </div>
        </div>

        <hr />
        <form asp-controller="LampModel" asp-action="AddNote">
            <div class="form-group">
                <label for="NoteArea"><b>Дополнительные сведения</b></label>
                <textarea placeholder="Новая заметка добавится к уже имеющимся..." class="form-control" id="NoteArea" name="NoteArea" style="height: 100px"></textarea>
            </div>

            <input type="hidden" name="id" value="@Model.Id" />

            <div class="form-group fix-btn-create">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
            <span class="text-success">@ViewBag.AddNoteSuccess</span>
        </form>
        <hr />
        <div class="col-md-12">
            <form method="post" enctype="multipart/form-data" asp-controller="FilesUpload" asp-action="Index">
                <div class="form-group">
                    <label for="files"><b>Выберите один или несколько файлов для загрузки:</b></label>
                    <input type="file" name="files" class="form-control" multiple />
                </div>

                <input type="hidden" name="id" value="@Model.Id" />
                <div class="form-group fix-btn-create">
                    <input type="submit" class="btn btn-primary" value="Загрузить" />
                    <span class="text-success">@ViewBag.FilesUploadSuccess</span>
                </div>
            </form>
        </div>
        <h5 style="margin-top:20px">Прикрепленные файлы</h5>
        <div class="col-md-12">
            <table class="table table-bordered align-middle">
                <thead>
                    <tr>
                        <th>Файл</th>
                        <th>Размер</th>
                        <th>Действие</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var fileRec in ViewBag.FileRecords) {

                        <tr>
                            <td><i class="@fileRec.Extension"></i> @fileRec.FileName</td>
                            <td>@fileRec.Size</td>
                            <td><a asp-action="DeleteAttachmentFile" asp-route-id="@Model.Id" asp-route-fileName="@fileRec.FileName" class="btn btn-danger">Удалить</a></td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IonosLedWebMvc.Ver2/Views/LampModel/Index.cshtml
@model IEnumerable<IonosLedWebMvc.Ver2.Dtos.LampModelDto>

@{
    ViewData["Title"] = "IndexLampModel";
}


<h2>Перечень моделей светильников со стоимостью работ (руб.)</h2>

@if (ViewData["UserActionResult"] != null) {
    <div class="alert-good fix-btn-create" style="background-color: @(ViewData["UserActionResult"].ToString().StartsWith(ViewData["OK"].ToString()) ? " forestgreen" : "indianred")">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>@ViewData["UserActionResult"]</strong>
    </div>
}

<p>
    <a asp-action="Create" class="btn btn-primary">Создать новую модель <i class="bi bi-plus-lg"></i></a>
</p>
<table class="table table-striped table-sm hide-for-loader">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModelName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sections)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CutPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DrillPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MountPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SolderPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssemblyPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CountReleased)
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModelName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sections)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CutPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DrillPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MountPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolderPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssemblyPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckPrice)
            </td>
                <td style="font-weight:600; color:darkblue">
                    @Html.DisplayFor(modelItem => item.CountReleased)
                </td>
            <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary btn-sm" title="Детализация">
                        <i class="bi bi-ticket-detailed"></i> Детали
                    </a> |
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm width-btn" title="Редактировать">
                        <i class="bi bi-pencil-fill"></i>
                    </a> |

                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm width-btn" title="Удалить">
                        <i class="bi bi-trash-fill"></i>
                        </a>
            </td>
        </tr>
}
    </tbody>
</table>

IonosLedWebMvc.Ver2/Views/LampModel/MyDocumentViewer.cshtml
@using GleamTech.AspNet.Core
@using GleamTech.DocumentUltimate
@using GleamTech.DocumentUltimate.AspNet
@using GleamTech.DocumentUltimate.AspNet.UI

@{
    Layout = null;
    ViewData["Title"] = "DetailsLampModel";
}


@{
    var documentViewer = new DocumentViewer
    {
        Width = 1620,
        Height = 880,
        Document = ViewData["FullPath"]?.ToString()
    };
}
<html>
    <head>
        @this.RenderHead(documentViewer)
    </head>
    <body>
        <h2>Просмотр документа</h2>
        <div class="text-center align-content-center">
            @this.RenderBody(documentViewer)
        </div>
    </body>
</html>